### PR TITLE
Mangle video orientation on SDP

### PR DESCRIPTION
**Pull request by mustafaboleken**
https://github.com/ant-media/Ant-Media-Server/issues/4574

### CODE REVIEW

**Comment by asharamseervi** [comment]
Hi @burak-58, can you please review this?

This is minor fix which may address Urgent Priority issue: https://github.com/ant-media/Ant-Media-Server/issues/4574
Thanks in advance.

**Comment by mekya** [comment]
Hi @asharamseervi ,

Yes, it's a good point. @burak-58 could you prioritize to merge this PR?

**Comment by USAMAWIZARD** [comment]
can we merge this if possible we are getting some tickets related to this

**Review by burak-58 — APPROVED** [review]

**Comment by USAMAWIZARD** [comment]
I am still getting hls rotated even after the pull request is merged

**Comment by USAMAWIZARD** [comment]
You have to add the following line after creating WebRTCClient instance to enable the change.
webRTCClient.setRemoveVideoRotationExtention(true);

**Pull request merged**
