### PR TITLE
Upload sdk to maven with ci

### PR DESCRIPTION
**Pull request by USAMAWIZARD**
added configuration and a CI pipeline for uploading to maven central

### CODE REVIEW

**Comment by USAMAWIZARD** [comment]
Deploy is Working fine the pipeline failed because of wrong credentials we will have to enter the credentials of ant media account

**Comment by mekya** [comment]
For some reason, I could not make this PR work and publish to the sonatype. I've started from scratch in this PR(https://github.com/ant-media/WebRTC-Android-SDK/pull/23). So I'm closing this PR.

**Comment by mekya** [comment]
It does not publish to the sonatype for me in my tests and Burak also mentioned that there is a problem in publishing.
Did you confirm that it's published to the sonatype?

For instance, I confirm that [aar files are here](https://oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~/io/antmedia/webrtc-android-framework/1.0.0-SNAPSHOT/webrtc-android-framework-1.0.0-20230426.124521-9.module) and I use the the framework in sample project by adding this dependency
``` 
implementation "io.antmedia:webrtc-android-framework:1.0.0-SNAPSHOT"
```

[as mentioned here ](https://github.com/ant-media/Ant-Media-Server/issues/5014)

**Comment by USAMAWIZARD** [comment]
yes I have confirmed it by using it as a dependency.
[here](https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/USAMAWIZARD/webrtc-android-framework/4.13.0-SNAPSHOT/) are the arr file

**Comment by mekya** [comment]
Yes, they are there. You're right. 

You made it work for you in your repository. That's good for testing. 

Just one feed forward, I expect you to finalize the work completely and make the PR ready to merge. I mean it does not publish to io.antmedia.webrtc-android-framework and it does not work for me even if I use the correct credentials. 

If you need something(key, password, etc) to finalize the work, please ask.

**Comment by USAMAWIZARD** [comment]
Sorry for my irresponsibility I will try to finalize things. Thanks for the feedback.

**Pull request closed without merging**
